import re
import difflib
import sys

def normalize_ida_code(code):
    """
    Removes or replaces address-specific nomenclature and metadata generated by IDA.
    """
    # 1. Normalize the function divider headers: //----- (0000C13A) -----
    code = re.sub(r'//-+\s+\([0-9a-fA-F]+\)\s+-+', '//----- (ADDR) -----', code)

    # 2. Normalize "control flows out of bounds to XXXX"
    code = re.sub(r'control flows out of bounds to [0-9a-fA-F]+', 'control flows out of bounds to ADDR', code)

    # 3. Replace sub_XXXX, loc_XXXX, off_XXXX, etc. with generic versions
    # Added 'v' for some variable names and 'arg_'/'var_' just in case
    addr_prefixes = r'(sub|loc|off|byte|word|dword|qword|unk|j_sub|nullsub|def|v|arg|var)'
    code = re.sub(rf'\b{addr_prefixes}_[0-9a-fA-F]+\b', r'\1_ADDR', code)

    # 4. Normalize stack variable offsets in comments: // [xsp+1Ch] [xbp-4h]
    code = re.sub(r'//\s*\[[a-zA-Z0-9+\s]+\]\s*\[[a-zA-Z0-9+\s-]+\]', '// [STACK_OFFSETS]', code)

    # 5. Generic Hex Address removal in comments
    # Matches hex strings (4+ chars) at the end of a comment line
    code = re.sub(r'//.*?\b[0-9a-fA-F]{4,}\b', lambda m: re.sub(r'[0-9a-fA-F]{4,}', 'ADDR', m.group(0)), code)
    
    # 6. Remove standalone address comments like "// 00401000"
    code = re.sub(r'//\s*[0-9a-fA-F]{4,}', '// ADDR', code)

    # 7. Clean up whitespace and empty lines
    code = "\n".join([line.strip() for line in code.splitlines() if line.strip()])

    return code

def compare_files(file1_path, file2_path):
    try:
        with open(file1_path, 'r', encoding='utf-8') as f1, \
             open(file2_path, 'r', encoding='utf-8') as f2:
            
            # Normalize both files
            code1 = normalize_ida_code(f1.read())
            code2 = normalize_ida_code(f2.read())

            # Generate Unified Diff
            diff = difflib.unified_diff(
                code1.splitlines(),
                code2.splitlines(),
                fromfile=file1_path,
                tofile=file2_path,
                lineterm=''
            )

            result = '\n'.join(diff)
            if not result:
                print("No logic differences found.")
            else:
                print(result)

    except Exception as e:
        print(f"Error: {e}")

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: python ida_diff.py <file1.c> <file2.c>")
    else:
        compare_files(sys.argv[1], sys.argv[2])